# Generated by Django 5.1.2 on 2024-10-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_remove_family_members_family_invite_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyGroup',
        ),
    ]
